### ISSUE TITLE
natural language audio 

### ISSUE THREAD

**Issue by betterze** [AndreyGuzhov/AudioCLIP#2]
Dear Andrey,

Thank you for your great for AudioCLIP, I really like it.

I look into the [nootbook](https://github.com/AndreyGuzhov/AudioCLIP/blob/master/demo/AudioCLIP.ipynb) and the [audio examples](https://github.com/AndreyGuzhov/AudioCLIP/tree/master/demo/audio). The audio examples mainly contain natural sound (of cat, alarm or coughing).

If I want to input human speaking, for example, a man says 'this is a photo of cat', will this audio retrieve images of cat when I input it to audioclip? Basically, if I input a sentence in form of audio rather than text (standard CLIP setting), will AudioCLIP retrieve the corresponding images? 

Thank you very much for your help.

Best Wishes,

Alex

**Comment by AndreyGuzhov** [comment]
Hi Alex,

Given an audio input in a form of spoken description of some concept, I expect that you could get meaningful results, although AudioCLIP wasn't trained in a speech-to-text setting. However, there could be such examples in the AudioSet dataset.

I plan to try out whether it'll work this way and update the thread once the results are ready. Thanks for the cool idea!

Best,
Andrey

**Comment by betterze** [comment]
Thank you for your reply. I will also try in this direction.
