### ISSUE TITLE
Is audioCLIP language independent?

### ISSUE THREAD

**Issue by parthplc** [AndreyGuzhov/AudioCLIP#3]
This is not a issue. I wanted to know whether Audio CLIP is language Independent or not?

**Comment by AndreyGuzhov** [comment]
Hi Parth,
 
From the implementation point of view, AudioCLIP is language independent. More specific, it supports any Unicode string as an input, which is not longer than 76 characters.
However, from the training data point of view, both vanilla CLIP and AudioCLIP were trained on mainly english samples.
Summarizing, AudioCLIP is language independent but works well for English, first of all.

Best,
Andrey
